Importing the Dependencies

In [77]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

Loading the dataset to a Pandas dataframe

In [78]:
credit_card_data = pd.read_csv('/content/creditcard_dataset.csv')

In [79]:
# printing the first 5 rows
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [80]:
# printing last 5 rows of dataframe
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

Getting information related to dataset

In [81]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [82]:
# checking number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [83]:
# showing the distribution of legit transaction & fraudulent transaction
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

**This Dataset is very highly Unbalanced dataset.**

*Class '0' represents --> Legit Transaction*

*Class '1' represents --> Fraudulent transaction*

In [84]:
# Separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [85]:
print(legit.shape)
print(fraud.shape)
print(credit_card_data.shape)

(284315, 31)
(492, 31)
(284807, 31)

In [86]:
# Getting some statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [87]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [88]:
# Comparing the values for both type of transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

***Under-Sampling***

**Building a sample dataset containing similar distribution of Legit Transaction and Fraudulent Transaction**

No.of Fraudulent Transaction  is --> 492

In [89]:
legit_sample = legit.sample(492)

Concatenating two sample datasets

In [90]:
# axis = 0 will concatenate datasets row-wise
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [91]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
78128,57382.0,-0.395948,1.123573,1.411860,-0.011056,0.031414,-0.766578,0.640766,0.034878,-0.738256,...,-0.194111,-0.501284,-0.010634,0.497132,-0.202767,0.040290,0.245557,0.091077,1.98,0
106987,70220.0,-1.784574,0.359855,0.867952,1.477501,-0.111213,0.041726,0.214445,0.670791,-0.423414,...,0.010679,0.350835,0.395751,0.227455,0.026332,-0.228337,0.494550,0.122294,97.25,0
196202,131405.0,2.177094,-1.742137,-0.252951,-1.755092,-1.526178,0.542347,-1.912169,0.254794,-0.897121,...,-0.094611,0.139646,0.305090,0.188244,-0.536596,-0.278579,0.052821,-0.033182,40.00,0
174987,122156.0,1.848601,-0.645630,0.406139,1.298795,-0.668487,1.473079,-1.414361,0.550861,1.677042,...,0.202505,0.951147,0.103174,0.154982,-0.144773,-0.539640,0.114166,-0.023542,15.99,0
96207,65659.0,-5.576185,-6.435046,2.438557,1.537200,4.856318,-1.706491,-3.693940,0.961225,0.886634,...,0.218604,0.004756,1.031994,-0.534008,-0.044608,1.173709,-0.558590,1.262944,99.94,0

In [92]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [93]:
#checking distribution of the sample dataset
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [94]:
# Comparing the values for both type of transactions for sample dataset
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,92778.128049,0.047244,0.041839,0.149393,-0.033966,0.055551,0.137995,-0.039843,0.082921,0.136239,...,-0.007587,-0.011768,0.001927,-0.013678,-0.024021,-0.008471,-0.005189,0.010963,0.011297,71.504898
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

**Splitting the data into Features and Targets**

In [95]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [96]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
78128    57382.0 -0.395948  1.123573  1.411860 -0.011056  0.031414 -0.766578
106987   70220.0 -1.784574  0.359855  0.867952  1.477501 -0.111213  0.041726
196202  131405.0  2.177094 -1.742137 -0.252951 -1.755092 -1.526178  0.542347
174987  122156.0  1.848601 -0.645630  0.406139  1.298795 -0.668487  1.473079
96207    65659.0 -5.576185 -6.435046  2.438557  1.537200  4.856318 -1.706491
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
78128   0.640766  0.034878 -0.738256  ...  0.145101 -0.194111 -0.501284
106987  0.214445  0.670791 -0.423414  ...  0.125568  0.010679  0.350835
196202 -1.912169  0.254794 -0.897121  ... -0.315686 -0.094611  0.139646
174987 -1.414361  0.550861  1.677042  ... -0.159782  0.202505  0.951147
96207  -3.693940  0.961225  0.886634  ...  0.923905  0.218604  0.004756
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
78128  -0.010634  0.497132 -0.202767  0.040290  0.245557  0.091077    1.98
106987  0.395751  0.227455  0.026332 -0.228337  0.494550  0.122294   97.25
196202  0.305090  0.188244 -0.536596 -0.278579  0.052821 -0.033182   40.00
174987  0.103174  0.154982 -0.144773 -0.539640  0.114166 -0.023542   15.99
96207   1.031994 -0.534008 -0.044608  1.173709 -0.558590  1.262944   99.94
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [97]:
print(Y)

78128     0
106987    0
196202    0
174987    0
96207     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

**Splitting into Training and Testing data**

In [98]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [99]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [100]:
#Scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**Model Initializing**

In [101]:
models = {
    "Logistic regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
}

**Traininng and Evaluating Models**

In [102]:
results_list = []

for name, model in models.items():
  model.fit(X_train, Y_train)

  Y_pred = model.predict(X_test)
  Y_pred_prob = model.predict_proba(X_test)[:,1]

  #Calculating the metrics
  print(f"[{name}]")
  print(f"  Accuracy:  {acc:.4f}")
  print(f"  Precision: {precision:.4f}")
  print(f"  Recall:    {rec:.4f}")
  print(f"  F1-Score:  {f1:.4f}")
  print(f"  ROC-AUC:   {roc_auc:.4f}")

[Logistic regression]
  Accuracy:  0.8985
  Precision: 0.9333
  Recall:    0.8571
  F1-Score:  0.8936
  ROC-AUC:   0.8983
[Random Forest]
  Accuracy:  0.8985
  Precision: 0.9333
  Recall:    0.8571
  F1-Score:  0.8936
  ROC-AUC:   0.8983
[XGBoost]
  Accuracy:  0.8985
  Precision: 0.9333
  Recall:    0.8571
  F1-Score:  0.8936
  ROC-AUC:   0.8983